# Generated by Django 4.2 on 2023-05-03 13:13

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission, Group

def create_groups_and_perms(apps, schema_migration):
    # Create permissions based on the User Model
    User = apps.get_model('login', 'User')

    content_type = ContentType.objects.get_for_model(User)
    advisor_permission = Permission.objects.create(
        codename='advisor_permissions',
        name='Rules for Advisors',
        content_type=content_type
    )
    farmer_permission = Permission.objects.create(
        codename='farmer_permissions',
        name='Rules for Farmers',
        content_type=content_type
    )
    earthworm_tech_permission = Permission.objects.create(
        codename='earthworm_tech_permissions',
        name='Rules for Earthworm Technicians',
        content_type=content_type
    )
    collector_permission = Permission.objects.create(
        codename='collector_permissions',
        name='Rules for Collectors',
        content_type=content_type
    )
    business_permission = Permission.objects.create(
        codename='business_permissions',
        name='Rules for Business',
        content_type=content_type
    )
    
    # Define groups to link User to
    # Each group has his very specific rules
    advisor_group = Group.objects.create(name='advisor')
    farmer_group = Group.objects.create(name='farmer')
    earthworm_tech_group = Group.objects.create(name='earthworm_tech')
    collector_group = Group.objects.create(name='collector')
    business_group = Group.objects.create(name='business')

    advisor_group.save()
    farmer_group.save()
    earthworm_tech_group.save()
    collector_group.save()
    advisor_group.save()

    advisor_group.permissions.set([advisor_permission])
    farmer_group.permissions.set([farmer_permission])
    earthworm_tech_group.permissions.set([earthworm_tech_permission])
    collector_group.permissions.set([collector_permission])
    business_group.permissions.set([business_permission])

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_perms)
    ]